name: Test and Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest  # You can change this to a different runner if needed

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up SSH key for GitHub Actions (Only if not already done)
    - name: Set up SSH key
      run: |
        if [ ! -f ~/.ssh/id_ed25519 ]; then
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          mv private_key.pem ~/.ssh/id_ed25519  
          export SSH_PRIVATE_KEY=~/.ssh/id_ed25519
          echo "@@ SSH private key has been set up."
        else
          echo "@@ SSH private key already exists, skipping setup."
          export SSH_PRIVATE_KEY=~/.ssh/id_ed25519
        fi

    # Step 3: Add Azure VM to known hosts (Only if not already done)
    - name: Add Azure VM to known hosts
      run: |
        mkdir -p ~/.ssh
        if ! grep -q "40.115.48.144" ~/.ssh/known_hosts; then
          ssh-keyscan -H 40.115.48.144 >> ~/.ssh/known_hosts 
          echo "@@ Azure VM added to known hosts."
        else
          echo "@@ Azure VM is already in known hosts, skipping addition."
        fi

    # Step 4: Run the env.sh script, stop the existing Node.js process, and restart it
    - name: Deploy to Azure VM
      run: |
        ssh -v -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@40.115.48.144 << 'EOF'
          set -e
          echo "@@ Step 4.1: Navigate to the project directory"
          cd /home/${{ secrets.AZURE_VM_USER }}/Project-ProgrammingIS 

          echo "@@ Step 4.2: Running env.sh script..."
          bash env.sh  # Run env.sh script

          echo "@@ 4.3: Kill any running Node.js process"
          pkill -f 'node server.js' || echo 'No running process found'

          echo "@@ 4.4: Git Pull"
          git pull origin main 

          echo "@@ 4.5: Start the server.js in the background and log output"
          nohup node server.js > server.log 2>&1 &
        EOF