name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out the repository code

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH key stored as a secret in GitHub

    - name: Deploy to Azure VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@13.80.26.188 << 'EOF'
          cd /home/useradmin/Project-ProgrammingIS  # Navigate to your project directory on the VM
          git pull origin main  # Pull latest changes from GitHub
          npm install  # Install dependencies (if using Node.js)
          # Optionally, you can restart a service or Docker container here
          # Example: docker-compose down && docker-compose up -d
        EOF
